### PR TITLE
Blinky RKH framwork on STM32

### PR DESCRIPTION
**Pull request by dariosb**

### CODE REVIEW

**Comment by dariosb** [comment]
Hi @rherrmannr 
I have updated the SCT plugin and the RKH generator to the recently 3.5.6 released versions and there has been some compatibility issue have occurred, i guess with xtext.

The model can no longer be displayed and the following errors occur:
1 - When the project is imported:
wspace_error
project_error

2 - When doubleclick on blinky.sct
plugin_error

**Comment by rherrmannr** [comment]
Hey @dariosb,

this is strange and should not have happened. I will have a look at the problem next week.

Greetings

**Comment by rherrmannr** [comment]
I've tested the example and got it running on the STM32. The LED is blinking!

According to your bug: We will release a new version of the RKH Generator, which is compatible with the neon release. The bug was a little tricky to find.

Some points to the index.html:
- Replace step 3.2 - This can be done via Marketplace. We will update the version to 3.5.6 in the marketplace. Especially, remove the update site.
- Remove step 3.3 (copy & paste this from the Linux blinky example)
- Remove step 3.4 - Will not be needed anymore with the new release


The rest looks good to me!

**Comment by dariosb** [comment]
Hi Robin

I really appreciate you've got running the example!!!
I´v pushed the documentation reviews.
I couldn´t test the plugin installation from Marketplace because the new release is not yet available for Neon.
When it´s done, I retry the installation process and update the capture into the documentation to correspond with the 3.5.6 version.

Greetings

**Pull request merged**
