### PR TITLE
Blinky RKH framwork on Linux CDT

### PR DESCRIPTION
**Pull request by leanfrancucci**

### CODE REVIEW

**Comment by rherrmannr** [comment]
Could you add some step by step instructions, of how to use the example in the index.html (For example the arduino example: https://github.com/Yakindu/examples/blob/master/com.yakindu.sct.examples.arduino.blinky/index.html).

1. Small introduction
2. Screenshot of the statechart
3. Whats required to compile & run the example
4. Steps to run the example

**Comment by rherrmannr** [comment]
Hey,
could you please tell me, when you're done?
I would try out the example and the step by step introductions and give you some feedback

**Comment by leanfrancucci** [comment]
I hope to finish the instuctions (index.html) today, but it would be nice if you give me your feedback as soon as possible.

**Comment by rherrmannr** [comment]
Hey,

I've got the first view on your example. I got some issues by getting the RKH framework.

At first, I've removed the RKH git repo and cloned a new one with ``git clone --recurse-submodules https://github.com/vortexmakes/RKH`` (This step is missing, too?)

Currently, I was able to import the example, download and run trazer and generate the sct code. But can't submodule rkh: ``git submodule init rkh/``. I also tried it with ``git submodule init RKH/``

This is the error (on german) ``:fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git`` means something like: ``fatal: Not a git repository (or of some parent repo)``


What am I doing wrong?

**Comment by rherrmannr** [comment]
ahh, I found the ``.gitmodules`` file. So cloning the rkh framework should be done out of the box by using ``git submodule init rkh/``?

But still, it does not work for me.

**Comment by rherrmannr** [comment]
Found the problem. This won't work with a copy of the project. I needed to clone your forked repo, check out your branch and execute everything in my /git folder. Then it worked.

This could be a problem later on, as we download the examples repo and do not clone the git repo for the end-user in the running product.

Independent of this, I got some compile errors. I'm using:
```
gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

and got error markers in ``Blinky.c``:
```
make all 
Building file: ../src/bsp/assert.c
Invoking: GCC C Compiler
gcc -D__LNXGNU__ -I../rkh/source/portable/80x86/linux_st/gnu -I../rkh/source/sma/inc -I../src/bsp -I../rkh/source/sm/inc -I../rkh/source/fwk/inc -I../rkh/source/mempool/inc -I../rkh/source/queue/inc -I../rkh/source/tmr/inc -I../rkh/source/trc/inc -I../src -I../src-gen -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/bsp/assert.d" -MT"src/bsp/assert.o" -o "src/bsp/assert.o" "../src/bsp/assert.c"
In file included from ../rkh/source/fwk/inc/rkhassert.h:77:0,
                 from ../rkh/source/fwk/inc/rkh.h:111,
                 from ../src/bsp/assert.c:55:
../rkh/source/fwk/inc/rkhfwk_module.h:122:35: warning: ‘m_name’ defined but not used [-Wunused-const-variable=]
         static RKHROM char *const m_name = __FILE__;
                                   ^
../src/bsp/assert.c:57:1: note: in expansion of macro ‘RKH_THIS_MODULE’
 RKH_THIS_MODULE
 ^~~~~~~~~~~~~~~
Finished building: ../src/bsp/assert.c
 
Building file: ../src/bsp/bsp_blinky.c
Invoking: GCC C Compiler
gcc -D__LNXGNU__ -I../rkh/source/portable/80x86/linux_st/gnu -I../rkh/source/sma/inc -I../src/bsp -I../rkh/source/sm/inc -I../rkh/source/fwk/inc -I../rkh/source/mempool/inc -I../rkh/source/queue/inc -I../rkh/source/tmr/inc -I../rkh/source/trc/inc -I../src -I../src-gen -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/bsp/bsp_blinky.d" -MT"src/bsp/bsp_blinky.o" -o "src/bsp/bsp_blinky.o" "../src/bsp/bsp_blinky.c"
In file included from ../rkh/source/fwk/inc/rkhassert.h:77:0,
                 from ../rkh/source/fwk/inc/rkh.h:111,
                 from ../src/bsp/bsp_blinky.c:59:
../rkh/source/fwk/inc/rkhfwk_module.h:122:35: warning: ‘m_name’ defined but not used [-Wunused-const-variable=]
         static RKHROM char *const m_name = __FILE__;
                                   ^
../src/bsp/bsp_blinky.c:62:1: note: in expansion of macro ‘RKH_THIS_MODULE’
 RKH_THIS_MODULE
 ^~~~~~~~~~~~~~~
Finished building: ../src/bsp/bsp_blinky.c
 
Building file: ../src/bsp/getopt.c
Invoking: GCC C Compiler
gcc -D__LNXGNU__ -I../rkh/source/portable/80x86/linux_st/gnu -I../rkh/source/sma/inc -I../src/bsp -I../rkh/source/sm/inc -I../rkh/source/fwk/inc -I../rkh/source/mempool/inc -I../rkh/source/queue/inc -I../rkh/source/tmr/inc -I../rkh/source/trc/inc -I../src -I../src-gen -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/bsp/getopt.d" -MT"src/bsp/getopt.o" -o "src/bsp/getopt.o" "../src/bsp/getopt.c"
Finished building: ../src/bsp/getopt.c
 
Building file: ../src/bsp/hook.c
Invoking: GCC C Compiler
gcc -D__LNXGNU__ -I../rkh/source/portable/80x86/linux_st/gnu -I../rkh/source/sma/inc -I../src/bsp -I../rkh/source/sm/inc -I../rkh/source/fwk/inc -I../rkh/source/mempool/inc -I../rkh/source/queue/inc -I../rkh/source/tmr/inc -I../rkh/source/trc/inc -I../src -I../src-gen -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/bsp/hook.d" -MT"src/bsp/hook.o" -o "src/bsp/hook.o" "../src/bsp/hook.c"
In file included from ../rkh/source/fwk/inc/rkhassert.h:77:0,
                 from ../rkh/source/fwk/inc/rkh.h:111,
                 from ../src/bsp/hook.c:62:
../rkh/source/fwk/inc/rkhfwk_module.h:122:35: warning: ‘m_name’ defined but not used [-Wunused-const-variable=]
         static RKHROM char *const m_name = __FILE__;
                                   ^
../src/bsp/hook.c:65:1: note: in expansion of macro ‘RKH_THIS_MODULE’
 RKH_THIS_MODULE
 ^~~~~~~~~~~~~~~
Finished building: ../src/bsp/hook.c
 
Building file: ../src/bsp/trace_io.c
Invoking: GCC C Compiler
gcc -D__LNXGNU__ -I../rkh/source/portable/80x86/linux_st/gnu -I../rkh/source/sma/inc -I../src/bsp -I../rkh/source/sm/inc -I../rkh/source/fwk/inc -I../rkh/source/mempool/inc -I../rkh/source/queue/inc -I../rkh/source/tmr/inc -I../rkh/source/trc/inc -I../src -I../src-gen -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/bsp/trace_io.d" -MT"src/bsp/trace_io.o" -o "src/bsp/trace_io.o" "../src/bsp/trace_io.c"
../src/bsp/trace_io.c: In function ‘trace_io_setConfig’:
../src/bsp/trace_io.c:122:17: warning: format not a string literal and no format arguments [-Wformat-security]
                 printf(helpMessage);
                 ^~~~~~
Finished building: ../src/bsp/trace_io.c
 
Building file: ../src/bsp/trace_io_tcp.c
Invoking: GCC C Compiler
gcc -D__LNXGNU__ -I../rkh/source/portable/80x86/linux_st/gnu -I../rkh/source/sma/inc -I../src/bsp -I../rkh/source/sm/inc -I../rkh/source/fwk/inc -I../rkh/source/mempool/inc -I../rkh/source/queue/inc -I../rkh/source/tmr/inc -I../rkh/source/trc/inc -I../src -I../src-gen -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/bsp/trace_io_tcp.d" -MT"src/bsp/trace_io_tcp.o" -o "src/bsp/trace_io_tcp.o" "../src/bsp/trace_io_tcp.c"
Finished building: ../src/bsp/trace_io_tcp.c
 
Building file: ../src-gen/Blinky.c
Invoking: GCC C Compiler
gcc -D__LNXGNU__ -I../rkh/source/portable/80x86/linux_st/gnu -I../rkh/source/sma/inc -I../src/bsp -I../rkh/source/sm/inc -I../rkh/source/fwk/inc -I../rkh/source/mempool/inc -I../rkh/source/queue/inc -I../rkh/source/tmr/inc -I../rkh/source/trc/inc -I../src -I../src-gen -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src-gen/Blinky.d" -MT"src-gen/Blinky.o" -o "src-gen/Blinky.o" "../src-gen/Blinky.c"
In file included from ../rkh/source/sm/inc/rkhsm.h:58:0,
                 from ../rkh/source/sma/inc/rkhsma.h:63,
                 from ../src-gen/Blinky.c:16:
../src-gen/Blinky.c:28:12: error: ‘evTout0’ undeclared here (not in a function)
  RKH_TRREG(evTout0, NULL, NULL, &RedLEDOff),
            ^
../rkh/source/fwk/inc/rkhitl.h:1697:9: note: in definition of macro ‘MKTRN’
         evt_, (RKH_GUARD_T)guard_, \
         ^~~~
../src-gen/Blinky.c:28:2: note: in expansion of macro ‘RKH_TRREG’
  RKH_TRREG(evTout0, NULL, NULL, &RedLEDOff),
  ^~~~~~~~~
../src-gen/Blinky.c:32:12: error: ‘evTout1’ undeclared here (not in a function); did you mean ‘evTout0’?
src-gen/subdir.mk:21: recipe for target 'src-gen/Blinky.o' failed
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
            ^
../rkh/source/fwk/inc/rkhitl.h:1697:9: note: in definition of macro ‘MKTRN’
         evt_, (RKH_GUARD_T)guard_, \
         ^~~~
../src-gen/Blinky.c:32:2: note: in expansion of macro ‘RKH_TRREG’
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
  ^~~~~~~~~
../src-gen/Blinky.c:32:12: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
            ^
../rkh/source/fwk/inc/rkhitl.h:1697:9: note: in definition of macro ‘MKTRN’
         evt_, (RKH_GUARD_T)guard_, \
         ^~~~
../src-gen/Blinky.c:32:2: note: in expansion of macro ‘RKH_TRREG’
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
  ^~~~~~~~~
../src-gen/Blinky.c:32:12: note: (near initialization for ‘RedLEDOff_trtbl[0].event’)
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
            ^
../rkh/source/fwk/inc/rkhitl.h:1697:9: note: in definition of macro ‘MKTRN’
         evt_, (RKH_GUARD_T)guard_, \
         ^~~~
../src-gen/Blinky.c:32:2: note: in expansion of macro ‘RKH_TRREG’
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
  ^~~~~~~~~
../src-gen/Blinky.c:32:12: error: initializer element is not constant
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
            ^
../rkh/source/fwk/inc/rkhitl.h:1697:9: note: in definition of macro ‘MKTRN’
         evt_, (RKH_GUARD_T)guard_, \
         ^~~~
../src-gen/Blinky.c:32:2: note: in expansion of macro ‘RKH_TRREG’
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
  ^~~~~~~~~
../src-gen/Blinky.c:32:12: note: (near initialization for ‘RedLEDOff_trtbl[0].event’)
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
            ^
../rkh/source/fwk/inc/rkhitl.h:1697:9: note: in definition of macro ‘MKTRN’
         evt_, (RKH_GUARD_T)guard_, \
         ^~~~
../src-gen/Blinky.c:32:2: note: in expansion of macro ‘RKH_TRREG’
  RKH_TRREG(evTout1, NULL, NULL, &RedLEDOn),
  ^~~~~~~~~
../rkh/source/fwk/inc/rkhitl.h:1714:13: warning: missing braces around initializer [-Wmissing-braces]
             { \
             ^
../rkh/source/sma/inc/rkhsma.h:352:42: note: in expansion of macro ‘MKSMA’
         static type RKH_SMA_NAME(name) = MKSMA(&RKH_SM_CONST_NAME(name), \
                                          ^~~~~
../src-gen/Blinky.c:38:1: note: in expansion of macro ‘RKH_SMA_CREATE’
 RKH_SMA_CREATE(Blinky, blinky, 0, HCAL, &RedLEDOn, Blinky_ToRedLEDOnExt0, NULL);
 ^~~~~~~~~~~~~~
make: *** [src-gen/Blinky.o] Error 1
```

**Comment by rherrmannr** [comment]
Some additional points:
- rename blinky to com.yakindu.sct.examples.rkh.blinky (project **and** folder)
- cannot use git submodule init as the user only will have the copy of the project
- Are we allowed to use the image with STM board? (Copyright)
- images are not displayed (except yakindu-rkh.png)

**Comment by leanfrancucci** [comment]
I will verify your comments

**Comment by rherrmannr** [comment]
You can use „org@. I will do the change if it is needed later on.

**Comment by rherrmannr** [comment]
Could you perhaps add your srg-gen folder? So I can compare the generated code and ensure that it compiles on my machine?

**Comment by rherrmannr** [comment]
Hey, 
I copied your src-gen folder into my workspace. Finally, I can compile and run the binary! :+1:

So, the next steps:
- merge the branch on our examples master
- update the rkh generator repo (With release 3.5.6)
- final test

If we succeed, we will put the example on our example release branch, so it's accessible for everyone, who's using SCT.

**Comment by rherrmannr** [comment]
If you want to try the example, you can choose the current branch for our example repo:

help -> YAKINDU SCT -> Example Wizard -> remote branch: Change from ``release`` to ``master``. 

Eventually, you have to change the storage location. For example instead of ``sct_example`` use ``sct_example_master``

**Pull request merged**
